version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  spring:
    image: khoulouddandani/sae5-projet-2:1-0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:3306/kaddem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "root",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    depends_on:
      - db
      -
volumes:
  db_data:




















